// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

interface Env {
    BACKEND?: string;
    LOCK_BACKEND?: boolean;
    REMOTE_CONFIG?: string;
    CHUNK_COUNT?: string;
    DB?: D1Database;
}
