// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

interface Env {
    BACKEND?: string;
    LOCK_BACKEND?: boolean;
    REMOTE_CONFIG?: string;
    PAGE_URL?: string;
    CHUNK_COUNT?: string;
}

declare module '*.html' {
    const html: string;
    export default html;
}
